export type DemoAssetKind = "real_capture" | "placeholder" | "concept";
export type DemoAssetChannel = "screenshot" | "poster" | "video" | "loop";

export interface DemoMedia {
  id: string;
  title: string;
  src: string;
  alt: string;
  kind: DemoAssetKind;
  channel: DemoAssetChannel;
  label: string;
  notes: string;
  aspect: "landscape" | "portrait" | "square";
  replacementPath: string;
}

export interface DemoVideoMedia extends Omit<DemoMedia, "channel"> {
  channel: "video";
  poster: string;
  videoSrc: string | null;
  duration: string;
  summary: string;
  category: string;
}

const media = {
  ipadHome: "/assets/demos/vitakiosk/ipad/home.png",
  ipadProductDetail: "/assets/demos/vitakiosk/ipad/product-detail.png",
  ipadLeaflet: "/assets/demos/vitakiosk/ipad/leaflet-enlarged.png",
  ipadShelf: "/assets/demos/vitakiosk/ipad/shelf-route.png",
  ipadAvatar: "/assets/demos/vitakiosk/ipad/avatar-vrm.png",
  kioskHome: "/assets/demos/vitakiosk/kiosk/home.png",
  kioskVoice: "/assets/demos/vitakiosk/kiosk/voice-flow.png",
  kioskShelf: "/assets/demos/vitakiosk/kiosk/shelf-navigation.png",
  vitaflowDashboard: "/assets/demos/vitaflow/dashboard.svg",
  vitaflowInventory: "/assets/demos/vitaflow/inventory.svg",
  vitaflowPurchase: "/assets/demos/vitaflow/purchase.svg",
  vitaflowPromotion: "/assets/demos/vitaflow/promotion.svg",
  vitaflowFollowUp: "/assets/demos/vitaflow/follow-up.svg",
  vitaflowPoster: "/assets/demos/vitaflow/poster.svg",
  kioskConceptPoster: "/assets/posters/vitakiosk-kiosk-concept.png",
  videoClinicQueue: "/assets/posters/video-clinic-queue.svg",
  videoPharmacyPartner: "/assets/posters/video-pharmacy-partner.svg",
  videoWebsiteStudio: "/assets/posters/video-ai-website-studio.svg",
  videoAcademy: "/assets/posters/video-ai-academy.svg",
};

export const demoAssetRoots = {
  vitakioskIpad: "/assets/demos/vitakiosk/ipad/",
  vitakioskKiosk: "/assets/demos/vitakiosk/kiosk/",
  vitaflow: "/assets/demos/vitaflow/",
  videos: "/assets/videos/",
  posters: "/assets/posters/",
  heroLoops: "/assets/loops/hero/",
} as const;

export const demoAssets = {
  vitakiosk: {
    ipadScreenshots: [
      {
        id: "kiosk-ipad-home",
        title: "VitaKiosk iPad home",
        src: media.ipadHome,
        alt: "Current VitaKiosk iPad landscape mock demo with VRM assistant, product panel, shelf map, promotion leaflet, and pharmacist assistance.",
        kind: "real_capture",
        channel: "screenshot",
        label: "Internal Lab Build",
        notes: "Captured from the existing 5175 kiosk mock demo with fictional mock data.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitakiosk/ipad/home.png",
      },
      {
        id: "kiosk-product-detail",
        title: "Product detail enlarge",
        src: media.ipadProductDetail,
        alt: "VitaKiosk enlarged product detail and summary state for a fictional Relief Balm mock product.",
        kind: "real_capture",
        channel: "screenshot",
        label: "Internal Lab Build",
        notes: "Shows the current product detail interaction with mock VitaFlow facts.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitakiosk/ipad/product-detail.png",
      },
      {
        id: "kiosk-leaflet-enlarged",
        title: "Promotion leaflet enlarged",
        src: media.ipadLeaflet,
        alt: "VitaKiosk enlarged fictional promotion leaflet overlay using no medical claim.",
        kind: "real_capture",
        channel: "screenshot",
        label: "Internal Lab Build",
        notes: "Fictional branch-valid leaflet evidence from the existing demo.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitakiosk/ipad/leaflet-enlarged.png",
      },
      {
        id: "kiosk-shelf-route",
        title: "Shelf navigation",
        src: media.ipadShelf,
        alt: "VitaKiosk shelf navigation route from entrance to Aisle 03 and Shelf A-03.",
        kind: "real_capture",
        channel: "screenshot",
        label: "Internal Lab Build",
        notes: "Route guidance display from the current kiosk mock.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitakiosk/ipad/shelf-route.png",
      },
      {
        id: "kiosk-avatar-vrm",
        title: "VRM assistant",
        src: media.ipadAvatar,
        alt: "VitaKiosk VRM assistant inside the current dark neon kiosk interface.",
        kind: "real_capture",
        channel: "screenshot",
        label: "Internal Lab Build",
        notes: "Avatar renderer proof with mock mode and no customer data.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitakiosk/ipad/avatar-vrm.png",
      },
    ] satisfies DemoMedia[],
    ipadVideos: [] as DemoVideoMedia[],
    largeKioskScreenshots: [
      {
        id: "kiosk-large-dashboard",
        title: "Large kiosk layout",
        src: media.kioskHome,
        alt: "Large landscape VitaKiosk demo layout with assistant, product facts, promotion, ERP provenance, and staff escalation.",
        kind: "real_capture",
        channel: "screenshot",
        label: "Internal Lab Build",
        notes: "Responsive current kiosk capture for large-format presentation.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitakiosk/kiosk/home.png",
      },
      {
        id: "kiosk-large-voice-flow",
        title: "Voice flow ready state",
        src: media.kioskVoice,
        alt: "VitaKiosk mock voice flow ready state with no customer data.",
        kind: "real_capture",
        channel: "screenshot",
        label: "Internal Lab Build",
        notes: "Use as a capture placeholder for future voice-flow video.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitakiosk/kiosk/voice-flow.png",
      },
    ] satisfies DemoMedia[],
    largeKioskVideos: [] as DemoVideoMedia[],
  },
  vitaflow: {
    screenshots: [
      {
        id: "vitaflow-dashboard-placeholder",
        title: "VitaFlow ERP dashboard",
        src: media.vitaflowDashboard,
        alt: "Placeholder VitaFlow ERP dashboard surface awaiting safe demo capture.",
        kind: "placeholder",
        channel: "screenshot",
        label: "Placeholder",
        notes: "Replace only with safe, non-private ERP demo data. Do not use customer, sales, or protected release files.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitaflow/dashboard.svg",
      },
      {
        id: "vitaflow-inventory-placeholder",
        title: "Inventory and stock movement",
        src: media.vitaflowInventory,
        alt: "Placeholder VitaFlow inventory and stock movement interface.",
        kind: "placeholder",
        channel: "screenshot",
        label: "Placeholder",
        notes: "Safe conceptual placeholder for branch-aware stock movement.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitaflow/inventory.svg",
      },
      {
        id: "vitaflow-purchase-placeholder",
        title: "Purchase workflow",
        src: media.vitaflowPurchase,
        alt: "Placeholder VitaFlow purchase workflow interface.",
        kind: "placeholder",
        channel: "screenshot",
        label: "Placeholder",
        notes: "Safe conceptual placeholder for purchase workflow.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitaflow/purchase.svg",
      },
      {
        id: "vitaflow-promotion-placeholder",
        title: "Promotion and price monitor",
        src: media.vitaflowPromotion,
        alt: "Placeholder VitaFlow promotion and price monitoring interface.",
        kind: "placeholder",
        channel: "screenshot",
        label: "Placeholder",
        notes: "Safe conceptual placeholder for price monitoring and reviewed promotions.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitaflow/promotion.svg",
      },
      {
        id: "vitaflow-follow-up-placeholder",
        title: "Customer follow-up",
        src: media.vitaflowFollowUp,
        alt: "Placeholder VitaFlow customer follow-up interface.",
        kind: "placeholder",
        channel: "screenshot",
        label: "Placeholder",
        notes: "Safe conceptual placeholder; replace only with demo data.",
        aspect: "landscape",
        replacementPath: "apps/site/public/assets/demos/vitaflow/follow-up.svg",
      },
    ] satisfies DemoMedia[],
    videos: [] as DemoVideoMedia[],
  },
  showcasePosters: [
    {
      id: "kiosk-concept-poster",
      title: "VitaKiosk concept poster",
      src: media.kioskConceptPoster,
      alt: "Cinematic VitaKiosk kiosk concept artwork used as a product showcase wrapper.",
      kind: "concept",
      channel: "poster",
      label: "Concept",
      notes: "Concept wrapper only; real demo screens are managed separately.",
      aspect: "landscape",
      replacementPath: "apps/site/public/assets/posters/vitakiosk-kiosk-concept.png",
    },
    {
      id: "vitaflow-poster-placeholder",
      title: "VitaFlow source-of-truth poster",
      src: media.vitaflowPoster,
      alt: "Placeholder VitaFlow source-of-truth poster.",
      kind: "placeholder",
      channel: "poster",
      label: "Placeholder",
      notes: "Use until a safe ERP poster or capture is approved.",
      aspect: "landscape",
      replacementPath: "apps/site/public/assets/demos/vitaflow/poster.svg",
    },
  ] satisfies DemoMedia[],
};

export const videoHubAssets: DemoVideoMedia[] = [
  {
    id: "clinic-queue-problem",
    title: "Clinic Queue Problem",
    src: media.videoClinicQueue,
    poster: media.videoClinicQueue,
    videoSrc: null,
    category: "problem",
    label: "Storyboard Placeholder",
    duration: "20s concept",
    summary: "A busy front desk becomes a product education handoff before the counter.",
    alt: "Storyboard placeholder for clinic queue problem video.",
    kind: "placeholder",
    channel: "video",
    notes: "Prompt ready; no generated or real patient footage committed.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/clinic-queue-problem.mp4",
  },
  {
    id: "pharmacy-partner-discovery",
    title: "Pharmacy Partner Discovery",
    src: media.videoPharmacyPartner,
    poster: media.videoPharmacyPartner,
    videoSrc: null,
    category: "partner",
    label: "Prompt Ready",
    duration: "20s concept",
    summary: "Connect product interest to participating pharmacy partners without endorsement claims.",
    alt: "Storyboard placeholder for pharmacy partner discovery video.",
    kind: "placeholder",
    channel: "video",
    notes: "Prompt ready; do not imply doctor or hospital endorsement.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/pharmacy-partner-discovery.mp4",
  },
  {
    id: "retail-pharmacy-promotion",
    title: "Retail Pharmacy Promotion",
    src: media.ipadLeaflet,
    poster: media.ipadLeaflet,
    videoSrc: null,
    category: "retail",
    label: "Internal Lab Build",
    duration: "20s concept",
    summary: "Turn silent promotions into guided product discovery with reviewed sponsored education.",
    alt: "VitaKiosk leaflet capture used as retail pharmacy promotion video poster.",
    kind: "real_capture",
    channel: "video",
    notes: "Poster is real capture; video file is not committed.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/retail-pharmacy-promotion.mp4",
  },
  {
    id: "vitakiosk-in-action",
    title: "VitaKiosk in Action",
    src: media.kioskHome,
    poster: media.kioskHome,
    videoSrc: null,
    category: "demo",
    label: "Internal Lab Build",
    duration: "Capture target",
    summary: "Voice, fuzzy search, product detail, shelf path, and pharmacist escalation.",
    alt: "Large VitaKiosk real capture used as video poster.",
    kind: "real_capture",
    channel: "video",
    notes: "Replace with edited demo capture after approval; no raw huge video committed.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/vitakiosk-in-action.mp4",
  },
  {
    id: "vitaflow-dashboard",
    title: "VitaFlow Dashboard",
    src: media.vitaflowDashboard,
    poster: media.vitaflowDashboard,
    videoSrc: null,
    category: "erp",
    label: "Placeholder",
    duration: "Capture target",
    summary: "Replace with safe demo dashboard footage only.",
    alt: "VitaFlow dashboard placeholder used as video poster.",
    kind: "placeholder",
    channel: "video",
    notes: "No private ERP data. Replace with safe demo capture only.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/vitaflow-dashboard.mp4",
  },
  {
    id: "ai-website-studio",
    title: "AI Website Studio",
    src: media.videoWebsiteStudio,
    poster: media.videoWebsiteStudio,
    videoSrc: null,
    category: "growth",
    label: "Storyboard Placeholder",
    duration: "20s concept",
    summary: "Outdated site transforms into a lead-ready AI website.",
    alt: "Storyboard placeholder for AI Website Studio video.",
    kind: "placeholder",
    channel: "video",
    notes: "Prompt ready; video asset not committed.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/ai-website-studio.mp4",
  },
  {
    id: "ai-academy",
    title: "AI Academy",
    src: media.videoAcademy,
    poster: media.videoAcademy,
    videoSrc: null,
    category: "training",
    label: "Storyboard Placeholder",
    duration: "20s concept",
    summary: "Random AI use becomes a practical business workflow.",
    alt: "Storyboard placeholder for AI Academy video.",
    kind: "placeholder",
    channel: "video",
    notes: "Prompt ready; video asset not committed.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/ai-academy.mp4",
  },
];
