import { demoVideoAssets, DemoVideoMedia } from "./demoAssets";

export const videoHubItems: DemoVideoMedia[] = [
  {
    id: "clinic-queue-problem",
    title: "Clinic Queue Problem",
    poster: demoVideoAssets.clinicQueue.poster,
    previewSrc: demoVideoAssets.clinicQueue.previewSrc,
    fullSrc: demoVideoAssets.clinicQueue.fullSrc,
    category: "problem",
    label: "Problem Film",
    status: "Storyboard",
    duration: "3s preview / 20s concept",
    summary: "A busy counter becomes a guided product education handoff.",
    alt: "Clinic queue storyboard video poster.",
    kind: "generated",
    channel: "video",
    notes: "Lightweight local preview loop. Replace with approved Higgsfield clip when available.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/higgsfield/clinic-queue-problem.webm",
  },
  {
    id: "pharmacy-partner-discovery",
    title: "Pharmacy Partner Discovery",
    poster: demoVideoAssets.pharmacyPartner.poster,
    previewSrc: demoVideoAssets.pharmacyPartner.previewSrc,
    fullSrc: demoVideoAssets.pharmacyPartner.fullSrc,
    category: "partner",
    label: "Partner Flow",
    status: "Prompt Ready",
    duration: "3s preview / 20s concept",
    summary: "Interest connects to participating pharmacy guidance without endorsement claims.",
    alt: "Pharmacy partner discovery video poster.",
    kind: "generated",
    channel: "video",
    notes: "Prompt ready; do not imply doctor or hospital endorsement.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/higgsfield/pharmacy-partner-discovery.webm",
  },
  {
    id: "retail-pharmacy-promotion",
    title: "Retail Pharmacy Promotion",
    poster: demoVideoAssets.retailPromotion.poster,
    previewSrc: demoVideoAssets.retailPromotion.previewSrc,
    fullSrc: demoVideoAssets.retailPromotion.fullSrc,
    category: "retail",
    label: "Campaign Film",
    status: "Prompt Ready",
    duration: "3s preview / 20s concept",
    summary: "Silent promotions turn into clear, reviewed product discovery.",
    alt: "Retail pharmacy promotion video poster.",
    kind: "generated",
    channel: "video",
    notes: "Sponsored education must be clearly labelled before deployment.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/higgsfield/retail-pharmacy-promotion.webm",
  },
  {
    id: "vitakiosk-interactive-demo",
    title: "VitaKiosk Interactive Demo",
    poster: demoVideoAssets.vitakioskInteractive.poster,
    previewSrc: demoVideoAssets.vitakioskInteractive.previewSrc,
    fullSrc: demoVideoAssets.vitakioskInteractive.fullSrc,
    category: "demo",
    label: "Interactive Demo",
    status: "Internal Lab Build",
    duration: "3s preview / capture target",
    summary: "Tap, scan, enlarge, route, and hand off inside the kiosk interface.",
    alt: "VitaKiosk interactive demo preview poster.",
    kind: "generated",
    channel: "video",
    notes: "Preview loop is generated; public demo is code-native and does not need the backend.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/higgsfield/vitakiosk-interactive-demo.webm",
  },
  {
    id: "vitaflow-source-of-truth",
    title: "VitaFlow Source of Truth",
    poster: demoVideoAssets.vitaflowSource.poster,
    previewSrc: demoVideoAssets.vitaflowSource.previewSrc,
    fullSrc: demoVideoAssets.vitaflowSource.fullSrc,
    category: "erp",
    label: "ERP Film",
    status: "Placeholder",
    duration: "3s preview / capture target",
    summary: "Product facts, stock, shelf, and campaign data stay tied to ERP.",
    alt: "VitaFlow source of truth video poster.",
    kind: "generated",
    channel: "video",
    notes: "Replace with safe ERP demo capture only.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/higgsfield/vitaflow-source-of-truth.webm",
  },
  {
    id: "ai-website-studio",
    title: "AI Website Studio",
    poster: demoVideoAssets.aiWebsite.poster,
    previewSrc: demoVideoAssets.aiWebsite.previewSrc,
    fullSrc: demoVideoAssets.aiWebsite.fullSrc,
    category: "growth",
    label: "Growth Film",
    status: "Prompt Ready",
    duration: "3s preview / 20s concept",
    summary: "A business site becomes an AI-ready lead and booking surface.",
    alt: "AI Website Studio video poster.",
    kind: "generated",
    channel: "video",
    notes: "Replace with approved Higgsfield or Remotion editorial when available.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/higgsfield/ai-website-studio.webm",
  },
  {
    id: "ai-academy",
    title: "AI Academy",
    poster: demoVideoAssets.aiAcademy.poster,
    previewSrc: demoVideoAssets.aiAcademy.previewSrc,
    fullSrc: demoVideoAssets.aiAcademy.fullSrc,
    category: "training",
    label: "Training Film",
    status: "Prompt Ready",
    duration: "3s preview / 20s concept",
    summary: "Teams move from random AI use to practical operating workflows.",
    alt: "AI Academy video poster.",
    kind: "generated",
    channel: "video",
    notes: "Replace with approved training campaign clip when available.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/higgsfield/ai-academy.webm",
  },
];
