import { demoVideoAssets, DemoVideoMedia } from "./demoAssets";

export const videoHubItems: DemoVideoMedia[] = [
  {
    id: "clinic-queue-problem",
    title: "Clinic Queue Problem",
    poster: demoVideoAssets.clinicQueue.poster,
    previewSrc: demoVideoAssets.clinicQueue.previewSrc,
    fullSrc: demoVideoAssets.clinicQueue.fullSrc,
    previewType: demoVideoAssets.clinicQueue.previewType,
    fullType: demoVideoAssets.clinicQueue.fullType,
    category: "problem",
    label: "Problem Film",
    status: "Demo Capture",
    duration: "15s clip",
    summary: "A busy counter becomes a guided product education handoff.",
    alt: "Clinic queue storyboard video poster.",
    kind: "generated",
    channel: "video",
    notes: "User-provided Jimeng clip. Product education before the counter; no diagnosis or prescription consultation claims.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/jimeng/clinic-queue-problem-storyboard.mp4",
  },
  {
    id: "pharmacy-partner-discovery",
    title: "Pharmacy Partner Discovery",
    poster: demoVideoAssets.pharmacyPartner.poster,
    previewSrc: demoVideoAssets.pharmacyPartner.previewSrc,
    fullSrc: demoVideoAssets.pharmacyPartner.fullSrc,
    previewType: demoVideoAssets.pharmacyPartner.previewType,
    fullType: demoVideoAssets.pharmacyPartner.fullType,
    category: "partner",
    label: "Partner Flow",
    status: "Demo Capture",
    duration: "15s clip",
    summary: "Interest connects to participating pharmacy guidance without endorsement claims.",
    alt: "Pharmacy partner discovery video poster.",
    kind: "generated",
    channel: "video",
    notes: "User-provided Jimeng clip; do not imply doctor or hospital endorsement.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/jimeng/pharmacy-partner-discovery-15s.mp4",
  },
  {
    id: "retail-pharmacy-promotion",
    title: "Retail Pharmacy Promotion",
    poster: demoVideoAssets.retailPromotion.poster,
    previewSrc: demoVideoAssets.retailPromotion.previewSrc,
    fullSrc: demoVideoAssets.retailPromotion.fullSrc,
    previewType: demoVideoAssets.retailPromotion.previewType,
    fullType: demoVideoAssets.retailPromotion.fullType,
    category: "retail",
    label: "Campaign Film",
    status: "Demo Capture",
    duration: "15s clip",
    summary: "Silent promotions turn into clear, reviewed product discovery.",
    alt: "Retail pharmacy promotion video poster.",
    kind: "generated",
    channel: "video",
    notes: "User-provided Jimeng clip. Sponsored education must be clearly labelled before deployment.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/jimeng/retail-pharmacy-promotion-15s.mp4",
  },
  {
    id: "ai-academy",
    title: "AI Academy",
    poster: demoVideoAssets.aiAcademy.poster,
    previewSrc: demoVideoAssets.aiAcademy.previewSrc,
    fullSrc: demoVideoAssets.aiAcademy.fullSrc,
    previewType: demoVideoAssets.aiAcademy.previewType,
    fullType: demoVideoAssets.aiAcademy.fullType,
    category: "training",
    label: "Training Film",
    status: "Demo Capture",
    duration: "32s clip",
    summary: "Teams move from random AI use to practical operating workflows.",
    alt: "AI Academy video poster.",
    kind: "generated",
    channel: "video",
    notes: "User-provided AI Academy training clip for the public media orbit.",
    aspect: "landscape",
    replacementPath: "apps/site/public/assets/videos/jimeng/ai-academy-32s.mp4",
  },
];
