from __future__ import annotations

from typing import Literal, TypedDict


PricingCategory = Literal["vitaflow", "vitakiosk", "aiLessons", "aiWebsite"]


class PricingItem(TypedDict):
    id: str
    name: str
    category: PricingCategory
    price_label: str
    cadence: str
    checkout_mode: Literal["subscription", "deposit", "one_time", "quote"]
    status_flow: list[str]
    includes: list[str]
    safety_note: str | None


PRICING_ITEMS: list[PricingItem] = [
    {
        "id": "vitaflow-starter-monthly",
        "name": "Starter",
        "category": "vitaflow",
        "price_label": "Subscription inquiry",
        "cadence": "Monthly framework",
        "checkout_mode": "subscription",
        "status_flow": [
            "draft",
            "checkout_created",
            "pending_payment",
            "active",
            "past_due",
            "cancelled",
            "manual_review",
        ],
        "includes": [
            "inventory",
            "stock movement",
            "branch-aware product data",
            "reports",
        ],
        "safety_note": None,
    },
    {
        "id": "vitaflow-growth-monthly",
        "name": "Growth",
        "category": "vitaflow",
        "price_label": "Subscription inquiry",
        "cadence": "Monthly framework",
        "checkout_mode": "subscription",
        "status_flow": [
            "draft",
            "checkout_created",
            "pending_payment",
            "active",
            "past_due",
            "cancelled",
            "manual_review",
        ],
        "includes": [
            "multi-branch operations",
            "price monitoring",
            "promotions",
            "customer follow-up",
        ],
        "safety_note": None,
    },
    {
        "id": "vitaflow-enterprise",
        "name": "Enterprise",
        "category": "vitaflow",
        "price_label": "Custom quote",
        "cadence": "Reviewed deployment",
        "checkout_mode": "quote",
        "status_flow": ["draft", "quote_requested", "manual_review", "active"],
        "includes": [
            "analytics",
            "role-aware operations",
            "deployment planning",
            "read-only integration planning",
        ],
        "safety_note": None,
    },
    {
        "id": "vitakiosk-local-edition",
        "name": "Local Edition",
        "category": "vitakiosk",
        "price_label": "Deposit framework",
        "cadence": "Hardware and setup quote",
        "checkout_mode": "deposit",
        "status_flow": [
            "draft",
            "quote_requested",
            "deposit_pending",
            "deposit_paid",
            "scheduled",
            "installed",
            "completed",
            "cancelled",
        ],
        "includes": [
            "product education",
            "promotion display",
            "shelf guidance",
            "staff escalation",
        ],
        "safety_note": (
            "General product education only. VitaKiosk does not diagnose, "
            "prescribe, or replace a pharmacist."
        ),
    },
    {
        "id": "vitakiosk-clinic-partner-campaign",
        "name": "Clinic Partner Campaign",
        "category": "vitakiosk",
        "price_label": "Campaign quote",
        "cadence": "Reviewed placement",
        "checkout_mode": "quote",
        "status_flow": ["draft", "quote_requested", "manual_review", "scheduled"],
        "includes": [
            "participating pharmacy guidance",
            "QR direction",
            "reviewed sponsored content",
            "campaign redemption workflow",
        ],
        "safety_note": "No hospital recommendation or doctor endorsement is implied.",
    },
    {
        "id": "vitakiosk-enterprise-deployment",
        "name": "Enterprise Deployment",
        "category": "vitakiosk",
        "price_label": "Custom quote",
        "cadence": "Reviewed deployment",
        "checkout_mode": "quote",
        "status_flow": ["draft", "quote_requested", "manual_review", "scheduled"],
        "includes": [
            "large kiosk deployment",
            "multi-site planning",
            "operations review",
            "support and training",
        ],
        "safety_note": None,
    },
    {
        "id": "ai-basics-1to1",
        "name": "AI Basics 1-to-1",
        "category": "aiLessons",
        "price_label": "Lesson booking",
        "cadence": "One-time session",
        "checkout_mode": "one_time",
        "status_flow": [
            "requested",
            "payment_pending",
            "paid",
            "confirmed",
            "completed",
            "rescheduled",
            "cancelled",
        ],
        "includes": ["AI basics", "prompt training", "practical AI workflow"],
        "safety_note": None,
    },
    {
        "id": "ai-pharmacy-workflow",
        "name": "AI for Pharmacy Workflow",
        "category": "aiLessons",
        "price_label": "Lesson booking",
        "cadence": "Workshop or 1-to-1",
        "checkout_mode": "one_time",
        "status_flow": [
            "requested",
            "payment_pending",
            "paid",
            "confirmed",
            "completed",
            "rescheduled",
            "cancelled",
        ],
        "includes": [
            "pharmacy AI workflow",
            "ERP-safe assistant habits",
            "staff escalation rules",
        ],
        "safety_note": None,
    },
    {
        "id": "codex-website-coaching",
        "name": "Codex / Website Build Coaching",
        "category": "aiLessons",
        "price_label": "Lesson booking",
        "cadence": "Coaching package",
        "checkout_mode": "one_time",
        "status_flow": [
            "requested",
            "payment_pending",
            "paid",
            "confirmed",
            "completed",
            "rescheduled",
            "cancelled",
        ],
        "includes": ["Codex workflow", "AI website build", "deployment checklist"],
        "safety_note": None,
    },
    {
        "id": "ai-content-video-workflow",
        "name": "AI Content & Video Workflow",
        "category": "aiLessons",
        "price_label": "Lesson booking",
        "cadence": "Creative workflow",
        "checkout_mode": "one_time",
        "status_flow": [
            "requested",
            "payment_pending",
            "paid",
            "confirmed",
            "completed",
            "rescheduled",
            "cancelled",
        ],
        "includes": ["AI video workflow", "storyboard prompts", "content calendar"],
        "safety_note": None,
    },
    {
        "id": "team-training-workshop",
        "name": "Team Training / Corporate Workshop",
        "category": "aiLessons",
        "price_label": "Team quote",
        "cadence": "Group training",
        "checkout_mode": "quote",
        "status_flow": ["requested", "quote_sent", "manual_review", "confirmed"],
        "includes": ["team workflow audit", "role-based training", "workshop materials"],
        "safety_note": None,
    },
    {
        "id": "landing-page-launch",
        "name": "Landing Page Launch",
        "category": "aiWebsite",
        "price_label": "Deposit framework",
        "cadence": "Project package",
        "checkout_mode": "deposit",
        "status_flow": [
            "inquiry",
            "quote_sent",
            "deposit_pending",
            "deposit_paid",
            "in_design",
            "in_development",
            "review",
            "launched",
            "completed",
            "cancelled",
        ],
        "includes": ["landing page", "lead capture", "domain setup", "launch support"],
        "safety_note": None,
    },
    {
        "id": "business-website",
        "name": "Business Website",
        "category": "aiWebsite",
        "price_label": "Project quote",
        "cadence": "Project package",
        "checkout_mode": "deposit",
        "status_flow": [
            "inquiry",
            "quote_sent",
            "deposit_pending",
            "deposit_paid",
            "in_design",
            "in_development",
            "review",
            "launched",
            "completed",
            "cancelled",
        ],
        "includes": ["website design", "SEO structure", "contact flow", "maintenance"],
        "safety_note": None,
    },
    {
        "id": "ai-website-chatbot",
        "name": "AI Website with Chatbot",
        "category": "aiWebsite",
        "price_label": "Project quote",
        "cadence": "AI-ready build",
        "checkout_mode": "deposit",
        "status_flow": [
            "inquiry",
            "quote_sent",
            "deposit_pending",
            "deposit_paid",
            "in_design",
            "in_development",
            "review",
            "launched",
            "completed",
            "cancelled",
        ],
        "includes": ["chatbot website", "knowledge base planning", "safe fallback"],
        "safety_note": None,
    },
    {
        "id": "booking-lead-generation-website",
        "name": "Booking / Lead Generation Website",
        "category": "aiWebsite",
        "price_label": "Project quote",
        "cadence": "Conversion build",
        "checkout_mode": "deposit",
        "status_flow": [
            "inquiry",
            "quote_sent",
            "deposit_pending",
            "deposit_paid",
            "in_design",
            "in_development",
            "review",
            "launched",
            "completed",
            "cancelled",
        ],
        "includes": ["booking flow", "lead intake", "follow-up planning"],
        "safety_note": None,
    },
    {
        "id": "custom-web-app",
        "name": "Custom Web App",
        "category": "aiWebsite",
        "price_label": "Custom quote",
        "cadence": "Reviewed build",
        "checkout_mode": "quote",
        "status_flow": ["inquiry", "quote_sent", "manual_review", "in_design"],
        "includes": ["custom workflow", "API plan", "security review"],
        "safety_note": None,
    },
]


def pricing_catalog() -> dict[str, object]:
    return {
        "provider": "mock",
        "currency": "MYR",
        "items": PRICING_ITEMS,
        "categories": {
            "vitaflow": "VitaFlow ERP Subscription",
            "vitakiosk": "VitaKiosk Order",
            "aiLessons": "AI Lessons",
            "aiWebsite": "AI Website Development",
        },
    }


def pricing_item_exists(item_id: str) -> bool:
    return any(item["id"] == item_id for item in PRICING_ITEMS)
