import type { Leaflet } from "./types";


export const MOCK_LEAFLETS: Leaflet[] = [
  {
    id: "MOCK-LF-PROMO-001",
    kind: "promotion",
    title: "Relief Balm Demo Leaflet",
    description: "Active branch promotion leaflet for Relief Balm.",
    branch_id: "SG-001",
    active: true,
    valid_from: "2025-01-01T00:00:00Z",
    valid_to: "2030-12-31T23:59:00Z",
    image_url: "/assets/leaflets/mock-relief-balm-promo.svg",
    product_ids: ["MOCK-P001"],
    category_tags: ["pain-relief", "topical"],
    display_priority: 10,
    source: "mock_vitaflow",
  },
  {
    id: "MOCK-LF-PROMO-002",
    kind: "promotion",
    title: "Supplement Savings Demo",
    description: "General active promotion leaflet for SG-001.",
    branch_id: "SG-001",
    active: true,
    valid_from: "2025-01-01T00:00:00Z",
    valid_to: "2030-12-31T23:59:00Z",
    image_url: "/assets/leaflets/mock-supplement-promo.svg",
    product_ids: [],
    category_tags: ["supplement", "wellness"],
    display_priority: 20,
    source: "mock_vitaflow",
  },
  {
    id: "MOCK-LF-CAMP-001",
    kind: "campaign",
    title: "Hydration Health Campaign",
    description: "Mock branch health campaign.",
    branch_id: "SG-001",
    active: true,
    valid_from: "2025-01-01T00:00:00Z",
    valid_to: "2030-12-31T23:59:00Z",
    image_url: "/assets/leaflets/mock-hydration-campaign.svg",
    product_ids: [],
    category_tags: ["hydration", "wellness"],
    display_priority: 30,
    source: "mock_vitaflow",
  },
];
